- name: Configure a Kubernetes node
  hosts: all
  become: true
  vars:
    k3s_version: latest
    cert_manager_version: latest
  tasks:
    - name: Ensure k3s config directory exists
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory

    - name: Install k3s config
      ansible.builtin.template:
        src: config.yaml.j2
        dest: /etc/rancher/k3s/config.yaml
      notify: Restart and enable k3s

    - name: Download k3s
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s
        mode: "0744"

    - name: Ensure k3s manifests directory exists
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server/manifests
        state: directory

    - name: Download a cert-manager manifest
      ansible.builtin.get_url:
        url: "https://github.com/cert-manager/cert-manager/releases/{{ 'latest/download' if cert_manager_version == 'latest' else 'download/' + cert_manager_version }}/cert-manager.yaml"
        dest: /var/lib/rancher/k3s/server/manifests/01-cert-manager.yaml

    - name: Deploy a ClusterIssuer manifest
      ansible.builtin.template:
        src: cluster-issuer.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/02-cluster-issuer.yaml

    - name: Install k3s
      ansible.builtin.command: /tmp/k3s
      environment:
        INSTALL_K3S_VERSION: "{{ '' if k3s_version == 'latest' else k3s_version }}"
      args:
        creates: /usr/local/bin/k3s
      notify: Restart and enable k3s

    - name: Start and enable k3s (self-healing in case handler's not triggered)
      ansible.builtin.systemd_service:
        name: k3s
        state: started
        enabled: true

    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ playbook_dir }}/kubeconfig"
        flat: true

    - name: Point kubeconfig at the public IP instead of localhost
      ansible.builtin.replace:
        path: "{{ playbook_dir }}/kubeconfig"
        regexp: '127\.0\.0\.1'
        replace: "{{ ansible_host }}"
      delegate_to: localhost
      become: false

  handlers:
    - name: Restart and enable k3s
      ansible.builtin.systemd_service:
        name: k3s
        state: restarted
        enabled: true
